CREATE DATABASE IF NOT EXISTS test;
USE test;

CREATE TABLE IF NOT EXISTS SISTEMA(
	nombre VARCHAR(36),
    PRIMARY KEY(nombre),
	numJuegos INT
);

CREATE TABLE IF NOT EXISTS USUARIOS(
	DNI CHAR(9) NOT NULL CHECK(DNI LIKE ('[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][A-Z]')),
    contrasena VARCHAR(36) NOT NULL,
    fecha_nacimiento DATE NOT NULL,
	nombre VARCHAR(36) NOT NULL,
	apellidos VARCHAR(255) NOT NULL,
	domicilio VARCHAR(255) NOT NULL,
    FOREIGN KEY (nombre) REFERENCES SISTEMA(nombre),
    PRIMARY KEY(DNI)
);

CREATE TABLE IF NOT EXISTS JUEGOS(
	nombreJuego VARCHAR(36),
    PRIMARY KEY(nombreJuego)
);
